export const team = [
	{
		id: 2,
		name: 'Barsha Emdad',
		image: 't1.jpg',
		position: 'Chief Project Officer',
	},
	{
		id: 1,
		name: 'Aysu Rahman',
		image: 't2.jpg',
		position: 'Managing Director & Co-founder',
	},
	{ name: 'Sheikh Shakib Ahmed', image: 't3.jpeg' },
	{ name: 'Kamal Rahman', image: 't4.jpeg' },
	{
		id: 3,
		name: 'Debi Brown',
		image: 't5.jpeg',
		position: 'Volunteer',
	},
	{ name: 'Diana Shalander', image: 't6.jpg' },
	{ name: 'Donna Jamila Crews', image: 't7.jpg' },
	{ name: 'Emama Emdad', image: 't8.jpg' },
	{ name: 'Esha Afreen', image: 't9.jpg' },
	{ name: 'Gretchen Rowe', image: 't10.jpg' },
	{ name: 'Jamal Rahman', image: 't12.jpg' },
	{ name: 'Khawaja Shamsuddin', image: 't13.jpg' },
	{ name: 'Nasreen Shamsuddin', image: 't14.jpg' },
	{ name: 'Naz Rahman', image: 't15.jpg' },
	{ name: 'Neal Emdad', image: 't16.jpeg' },
	{ name: 'Nuzhat Mustafa', image: 't17.jpeg' },
	{ name: 'Sally Jo Gilbert de Vargas', image: 't18.jpg' },
	{ name: 'Sufi Ara Parikh', image: 't19.jpeg' },
	{ name: 'Suraiya Emdad', image: 't20.jpeg' },
	{ name: 'Tracy Nolan', image: 't21.jpeg' },
	{ name: 'Zach Brown', image: 't22.jpeg' },
];
